intake/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from intake.views import accounts, asylee, campaign, headofhousehold, intakebus
from intake.views import donate, location, medical, organization, reports, requestqueue, signup, sponsor, travelplan, users, views

urlpatterns = [
    # path('', central_dispatch.dispatch, name='dispatch'),
    path('', views.HomePageView.as_view(), name='home'),
    path('requestqueue', requestqueue.request_queue, name='request queue'),
    # path('token/<int:poc_id>/', tokens.token_generate, name='org token generate'),
    # path('organization', organization.OrganizationCreationView.as_view(), name='families'),
    path('signup/', accounts.SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', signup.ActivateAccount.as_view(), name='activate'),
    path('cardtest', views.cardtest, name='card test'),

    path('organization/', include(([
        path('list/<user_id>/', organization.OrganizationListView.as_view(), name='list'),
        path('add/<user_id>', organization.OrganizationCreateView.as_view(), name='add'),
        path('<org_id>/detail', organization.OrganizationDetail.as_view(), name='detail'),
        # path('<org_id>/detail', organization.OrganizationDetailView.as_view(), name='detail'),
        path('<org_id>/overview', organization.OrganizationOverview.as_view(), name='overview'),
        path('<org_id>/edit', organization.OrganizationEditView.as_view(), name='edit'),
        path('<org_id>/update', organization.OrganizationUpdate.as_view(), name='update'),
        # path('', organization.OrganizationListView.as_view(), name='list'),
        # path('add/', organization.OrganizationCreationView.as_view(), name='add'),
        # path('<org_id>/', organization.OrganizationDetailView.as_view(), name='detail'),
        # path('campaigns/<org_id>/', campaign.CampaignListView.as_view(), name='campaigns'),
        path('approve/<int:queue_id>/', requestqueue.organization_approve, name='approve'),
        path('decline/<int:queue_id>/', requestqueue.organization_decline, name='decline'),
    ], 'intake'), namespace='organization')),

    path('location/', include(([
        # path('list/<org_id>', location.LocationList.as_view(), name='list'),
        path('add/<org_id>', location.LocationCreateView.as_view(), name='add'),
        # path('<loc_id>/detail', location.LocationDetailView.as_view(), name='detail'),
        path('<loc_id>/overview', location.LocationOverview.as_view(), name='overview'),
        path('<loc_id>/detail', location.LocationDetail.as_view(), name='detail'),
        path('<loc_id>/update', location.LocationUpdate.as_view(), name='update'),
        path('<loc_id>/delete', location.LocationDelete.as_view(), name='delete'),
        # path('<loc_id>/', location.LocationListView.as_view(), name='list'),
        # path('<loc_id>/', location.LocationDetailView.as_view(), name='detail'),
        # path('add/<org_id>/', location.LocationCreationView.as_view(), name='add'),
        # path('edit/<loc_id>/', location.LocationUpdateView.as_view(), name='edit'),
    ], 'intake'), namespace='location')),

    path('intakebus/', include(([
        path('list/<loc_id>', intakebus.IntakeBusListView.as_view(), name='list'),
        path('add/<loc_id>', intakebus.IntakeBusCreateView.as_view(), name='add'),
        # path('<ib_id>/detail', intakebus.IntakeBusDetailView.as_view(), name='detail'),
        path('<ib_id>/detail', intakebus.IntakeBusDetail.as_view(), name='detail'),
        path('<ib_id>/overview', intakebus.IntakeBusOverview.as_view(), name='overview'),
        path('<ib_id>/update', intakebus.IntakeBusUpdate.as_view(), name='update'),
        path('<ib_id>/delete', intakebus.IntakeBusDelete.as_view(), name='delete'),
        # path('<ib_id>/', intakebus.IntakeBusDetailView.as_view(), name='detail'),
        # path('add/<loc_id>/', intakebus.IntakeBusCreationView.as_view(), name='add'),
    ], 'intake'), namespace='intakebus')),

    # path('family/', include(([
    #     path('list/<ib_id>', family.FamilyListView.as_view(), name='list'),
    #     path('add/<ib_id>', family.FamilyCreateView.as_view(), name='add'),
    #     path('<fam_id>/detail', family.FamilyDetailView.as_view(), name='detail'),
    #     path('<fam_id>/edit', family.FamilyEditView.as_view(), name='edit'),
    #     # path('<fam_id>/', family.FamilyDetailView.as_view(), name='detail'),
    #     # path('add/<ib_id>/', family.FamilyCreationView.as_view(), name='add'),
    # ], 'intake'), namespace='family')),

    path('headofhousehold/', include(([
        path('list/<ib_id>', headofhousehold.HeadOfHouseholdListView.as_view(), name='list'),
        path('add/<ib_id>', headofhousehold.HeadOfHouseholdCreateView.as_view(), name='add'),
        # path('<hoh_id>/detail', headofhousehold.HeadOfHouseholdDetailView.as_view(), name='detail'),
        path('<hoh_id>/detail', headofhousehold.HeadOfHouseholdDetail.as_view(), name='detail'),
        path('<hoh_id>/overview', headofhousehold.HeadOfHouseholdOverview.as_view(), name='overview'),
        path('<hoh_id>/update', headofhousehold.HeadOfHouseholdUpdate.as_view(), name='update'),
        path('<hoh_id>/delete', headofhousehold.HeadOfHouseholdDelete.as_view(), name='delete'),
        path('<hoh_id>/itinerary', headofhousehold.ItineraryDetail.as_view(), name='itinerary'),
        path('followup/health/<hoh_id>', headofhousehold.HeadOfHouseholdHealthFollowUpTemplateView.as_view(), name='health follow up'),
        path('<hoh_id>/add/<need_id>', headofhousehold.AddNeedToHousehold, name='add need'),
        path('<hoh_id>/satisfy/<need_id>', headofhousehold.SatisfyNeedForHousehold, name='satisfy need'),
        # path('<hoh_id>/', headofhousehold.HeadOfHouseholdDetailView.as_view(), name='detail'),
        # path('add/<ib_id>/', headofhousehold.HeadOfHouseholdCreationView.as_view(), name='add'),
    ], 'intake'), namespace='headofhousehold')),

    path('asylee/', include(([
        path('list/<hoh_id>', asylee.AsyleeListView.as_view(), name='list'),
        path('add/<hoh_id>', asylee.AsyleeCreateView.as_view(), name='add'),
        # path('<asy_id>/detail', asylee.AsyleeDetailView.as_view(), name='detail'),
        path('<asy_id>/detail', asylee.AsyleeDetail.as_view(), name='detail'),
        path('<asy_id>/overview', asylee.AsyleeOverview.as_view(), name='overview'),
        path('<asy_id>/update', asylee.AsyleeUpdate.as_view(), name='update'),
        path('<asy_id>/delete', asylee.AsyleeDelete.as_view(), name='delete'),
        # path('followup/health /<asy_id>', asylee.AsyleeHealthFollowUpFormView.as_view(), name='health follow up'),
        path('followup/<asy_id>', asylee.AsyleeHealthFollowUpTemplateView.as_view(), name='health follow up'),
        # path('<asylee_id>/', asylee.AsyleeDetailView.as_view(), name='detail'),
        # path('add/<hoh_id>/', asylee.AsyleeCreationView.as_view(), name='add'),
    ], 'intake'), namespace='asylee')),

    path('sponsor/', include(([
        path('list/<hoh_id>', sponsor.SponsorListView.as_view(), name='list'),
        path('add/<hoh_id>', sponsor.SponsorCreateView.as_view(), name='add'),
        path('<spon_id>/detail', sponsor.SponsorDetailView.as_view(), name='detail'),
        path('<spon_id>/update', sponsor.SponsorUpdate.as_view(), name='update'),
        path('<spon_id>/delete', sponsor.SponsorDelete.as_view(), name='delete'),
        # path('<sponsor_id>/', sponsor.SponsorDetailView.as_view(), name='detail'),
        # path('add/<hoh_id>/', sponsor.SponsorCreationView.as_view(), name='add'),
    ], 'intake'), namespace='sponsor')),

    path('travelplan/', include(([
        path('list/<hoh_id>', travelplan.TravelPlanListView.as_view(), name='list'),
        path('add/<hoh_id>', travelplan.TravelPlanCreateView.as_view(), name='add'),
        path('<tp_id>/detail', travelplan.TravelPlanDetailView.as_view(), name='detail'),
        path('<tp_id>/update', travelplan.TravelPlanUpdate.as_view(), name='update'),
        path('<tp_id>/delete', travelplan.TravelPlanDelete.as_view(), name='delete'),
        path('followup/<tp_id>', travelplan.TravelModeFollowUpTemplateView.as_view(), name='travel follow up'),
        # path('<tp_id>/', travelplan.TravelPlanDetailView.as_view(), name='detail'),
        # path('add/<hoh_id>/', travelplan.TravelPlanCreationView.as_view(), name='add'),
    ], 'intake'), namespace='travelplan')),

    # path('medical/', include(([
    #     path('list/<asy_id>', medical.MedicalListView.as_view(), name='list'),
    #     path('add/<asy_id>', medical.MedicalCreateView.as_view(), name='add'),
    #     path('<med_id>/detail', medical.MedicalDetailView.as_view(), name='detail'),
    #     path('<med_id>/update', medical.MedicalUpdate.as_view(), name='update'),
    #     path('<med_id>/delete', medical.MedicalDelete.as_view(), name='delete'),
    #     # path('<med_id>/', medical.MedicalDetailView.as_view(), name='detail'),
    #     # path('add/<asylee_id>/', medical.MedicalCreationView.as_view(), name='add'),
    # ], 'intake'), namespace='medical')),

    path('campaign/', include(([
        path('list/<user_id>', campaign.CampaignListView.as_view(), name='list'),
        path('add/<user_id>', campaign.CampaignCreateView.as_view(), name='add'),
        path('<camp_id>/detail', campaign.CampaignDetailView.as_view(), name='detail'),
        # path('add/', campaign.CampaignCreationView.as_view(), name='add'),
        # path('<camp_id>/', campaign.CampaignDetailView.as_view(), name='detail'),
        path('affiliate/<camp_id>/', campaign.affiliate, name='affiliate'),
    ], 'intake'), namespace='campaign')),

    path('user/', include(([
    #     path('', point_of_contact.QuizListView.as_view(), name='quiz_list'),
        path('request_permission/', users.request_permission_to_create_organization, name='request permission'),

ristra/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import RedirectView

from intake.views import accounts, signup, site_coordinator, team_leads, volunteers

urlpatterns = [
    path('', include('intake.urls')),
    path('admin/', admin.site.urls),
    path('s/', include('shortener.urls')),
    path('accounts/password_change/', accounts.change_password, name='change_password'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('favicon.ico', RedirectView.as_view(url='/static/intake/images/favicon.ico')),
    # path('accounts/signup/', signup.SignUpView.as_view(), name='signup'),
    # path('accounts/signup/volunteer/', volunteers.VolunteerSignUpView.as_view(), name='volunteer_signup'),
    # path('accounts/signup/teamlead/', team_leads.TeamLeadSignUpView.as_view(), name='team_lead_signup'),
    # path('accounts/signup/sitecoordinator/', site_coordinator.SiteCoordinatorSignUpView.as_view(), name='site_coordinator_signup'),
]

intake/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from intake.models import VolunteerTypes

class SignUpForm(UserCreationForm):
    name = forms.CharField(help_text="First and last name", max_length=300)
    email = forms.EmailField(max_length=300, help_text='Required. Inform a valid email address.')
    phone_number = forms.CharField(help_text="Phone number", max_length=300)
    volunteer_type = forms.ModelMultipleChoiceField(queryset=VolunteerTypes.objects.all())

    class Meta:
        model = User
        fields = ('username', 'name', 'email', 'phone_number', 'volunteer_type', 'password1', 'password2',)

intake/forms/asylee.py
from django import forms
from intake.choices import COVID_VACCINE_CHOICES
from intake.forms.forms import DateInput
from intake.models import Asylee

# Create your forms here.
class AsyleeForm(forms.ModelForm):
    # a_number = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={'placeholder': 'A-'},
    #     )
    # )
    phone_number = forms.CharField(
        required=False
    )
    date_of_birth = forms.DateField(
        help_text="MM/DD/YYYY",
        widget=DateInput(
            attrs={
                'min':'1900-01-01',
                'max':'2100-12-31',
                'pattern':'[0-9]{4}-[0-9]{2}-[0-9]{2}',
            }
        ),
    )
    is_currently_sick = forms.BooleanField(
        # help_text='Is sick now'
        required=False
    )
    shirt_size = forms.CharField(
        help_text="E.g. infant, 2T, children's large, medium, XL",
    )
    class Meta:
        model = Asylee
        fields = ['name','a_number','sex','date_of_birth','phone_number','had_covid_disease','had_covid_vaccine', 'is_currently_sick', 'needs_medical_attention','shirt_size','pant_size','shoe_size','underwear_size','notes',]

class AsyleeHealthFollowUpForm(forms.ModelForm):
    VACCINATION_CHOICES = [
        (0,'0'),
        (1,'1'),
        (2,'2'),
    ]
    covid_vaccine_shots = forms.ChoiceField(
        choices=VACCINATION_CHOICES,
        required=True,
    )
    vaccine_received = forms.ChoiceField(
        choices=COVID_VACCINE_CHOICES,
        required=True,
    )
    class Meta:
        model = Asylee
        fields = ['vaccine_received','covid_vaccine_doses','sick_covid','sick_other',]

class AsyleeVaccineForm(forms.ModelForm):
    VACCINATION_CHOICES = [
        (0,'0'),
        (1,'1'),
        (2,'2'),
    ]
    covid_vaccine_doses = forms.ChoiceField(
        choices=VACCINATION_CHOICES,
        required=True,
    )
    vaccine_received = forms.ChoiceField(
        choices=COVID_VACCINE_CHOICES,
        required=True,
    )
    class Meta:
        model = Asylee
        fields = ['vaccine_received','covid_vaccine_doses',]

class AsyleeSickForm(forms.ModelForm):
    class Meta:
        model = Asylee
        fields = ['sick_covid','sick_other',]

intake/forms/campaign.py
from django import forms
from intake.forms.forms import DateTimeInput
from intake.models import Campaign

# Create your forms here.
class CampaignForm(forms.ModelForm):
    expiration_date = forms.DateTimeField(
        help_text='Time at which this link will expire',
        widget=DateTimeInput(),
    )

    class Meta:
        model = Campaign
        fields = ['organization','expiration_date',]

intake/forms/donate.py
from django import forms
from intake.models import Donate, Organization

# Create your forms here.
class DonateForm(forms.ModelForm):
    class Meta:
        model = Donate
        fields = ['name', 'location','url','description',]

intake/forms/family.py
from django import forms
from intake.choices import LANGUAGE_CHOICES
from intake.forms.forms import DateInput
from intake.models import HeadOfHousehold, IntakeBus, Language

# Create your forms here.
class FamilyForm(forms.ModelForm):
    phone_number = forms.CharField(
        required=False
    )
    date_of_birth = forms.DateField(
        help_text="MM/DD/YYYY",
        widget=DateInput(),
    )
    languages = forms.ModelMultipleChoiceField(
        help_text='Ctrl-Click to select multiple; Cmd-Click on Mac',
        queryset = Language.objects.all(),
        required=True,
        label='Languages spoken'
    )

    # def __init__(self, *args, **kwargs):
    #     vol_avails = kwargs.pop('vol_avail')
    #     super(self.__class__, self).__init__(*args, **kwargs)
    #     self.fields['intake_by'].queryset = vol_avails

    class Meta:
        model = HeadOfHousehold
        fields = ['name','sex','date_of_birth','phone_number','tsa_done','legal_done','languages','lodging','destination_city','state','days_traveling','days_detained','country_of_origin','notes',]

intake/forms/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from datetime import datetime
from intake.models import Capacity, Language

class DateInput(forms.DateInput):
    input_type = "date"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%d"
        super().__init__(**kwargs)


class TimeInput(forms.TimeInput):
    input_type = "time"


class DateTimeInput(forms.DateTimeInput):
    input_type = "datetime-local"

    def __init__(self, **kwargs):
        kwargs["format"] = "%Y-%m-%dT%H:%M"
        super().__init__(**kwargs)


class SignUpForm(UserCreationForm):
    name = forms.CharField(help_text="First and last name", max_length=300)
    email = forms.EmailField(max_length=300)
    phone_number = forms.CharField(help_text="Phone number", max_length=300)
    languages = forms.ModelMultipleChoiceField(
        help_text='Ctrl-Click to select multiple; Cmd-Click on Mac',
        queryset = Language.objects.all(),
        required=True
    )
    capacities = forms.ModelMultipleChoiceField(
        help_text='Ctrl-Click to select multiple; Cmd-Click on Mac',
        queryset = Capacity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
    # languages = forms.ModelMultipleChoiceField(queryset=Languages.objects.all())
    # capacities = forms.ModelMultipleChoiceField(queryset=Capacities.objects.all())

    class Meta:
        model = User
        # fields = ('username', 'name', 'email', 'phone_number', 'languages', 'capacities', 'password1', 'password2',)
        exclude = ('campaigns', )

intake/forms/intakebus.py
from django import forms
from intake.forms.forms import DateTimeInput
from intake.models import IntakeBus

# Create your forms here.
class IntakeBusForm(forms.ModelForm):
    arrival_time = forms.DateTimeField(
        widget=DateTimeInput(
            attrs={
                'min':'2020-01-01T00:00:00',
                'max':'2100-12-31T00:00:00',
                'pattern':'[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}',
            }
        ),
    )

    class Meta:
        model = IntakeBus
        fields = ['origin','state','arrival_time','number','notes',]

intake/templates/intake/report_list.html
{% extends 'intake/base.html' %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

{% load my_tags %}

{% block title %}{{ report_title}} :: Ristra Refuge{% endblock %}

{% block content %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<style>
#myInput {
  background-image: url('/css/searchicon.png'); /* Add a search icon to input */
  background-position: 10px 12px; /* Position the search icon */
  background-repeat: no-repeat; /* Do not repeat the icon image */
  width: 100%; /* Full-width */
  font-size: 16px; /* Increase font-size */
  padding: 12px 20px 12px 40px; /* Add some padding */
  border: 1px solid #ddd; /* Add a grey border */
  margin-bottom: 12px; /* Add some space below the input */
}
</style>

<!--<div class="telmon2-outlier warning red" style="text-align:center;">
    {{message}}
</div>-->

<h1 class="text-center">{{user.profile.affiliation.name}} {{ report_title }}</h1><br>
  <div class="card">
    <table id="asylee_list" class="table-sm table table-striped mb-0">
      <thead>
        <tr>
            <div class="container" style="padding: 10px 0px">
            <div class="row">
            <div class="col-sm-3">
                <!-- <input type="text" id="search_asylees" list="asylees" placeholder="Filter by asylee"> -->
                <input type="text" id="asylees_search" onkeyup="AsyleeSearch()" placeholder="Search by asylee…" title="Type in a name">
            </div>
            <div class="col-sm-3">
                <!-- <input type="text" id="search_households" placeholder="Filter by household"> -->
                <input type="text" id="households_search" onkeyup="HouseholdSearch()" placeholder="Search by household…" title="Type in a name">
            </div>
            <div class="col-sm-3">
                <!-- <input type="text" id="search_intakebuses" list="intakebuses" placeholder="Bus search"> -->
                <input type="text" id="destination_search" onkeyup="DestinationSearch()" placeholder="Search by destination…" title="Type in a name">
            </div>
            <div class="col-sm-3">
                <input type="text" id="search" placeholder="Overall search">
            </div>
            </div>
            </div>
        </tr>
        <tr>
          <th><a href="?sort_by={% if sorting.ascending and sorting.sorting == 'asylee' %}-{% endif %}asylee">
              Asylee Name
              {% if sorting.sorting == 'asylee' %}{% if sorting.ascending %}↑{% else %}↓{% endif %}{% else %}⇡{% endif %}</a>
          </th>
          <th><a href="?sort_by={% if sorting.ascending and sorting.sorting == 'household' %}-{% endif %}household">
              Household of
              {% if sorting.sorting == 'household' %}{% if sorting.ascending %}↑{% else %}↓{% endif %}{% else %}⇡{% endif %}</a>
          </th>
          <th><a href="?sort_by={% if sorting.ascending and sorting.sorting == 'lodging' %}-{% endif %}lodging">
              Rm #
              {% if sorting.sorting == 'lodging' %}{% if sorting.ascending %}↑{% else %}↓{% endif %}{% else %}⇡{% endif %}</a>
          </th>
          <th><a href="?sort_by={% if sorting.ascending and sorting.sorting == 'destination' %}-{% endif %}destination">
              Dest.
              {% if sorting.sorting == 'destination' %}{% if sorting.ascending %}↑{% else %}↓{% endif %}{% else %}⇡{% endif %}</a>
          </th>
          <th><a href="?sort_by={% if sorting.ascending and sorting.sorting == 'arrival_time' %}-{% endif %}arrival_time">
              Here Since
              {% if sorting.sorting == 'arrival_time' %}{% if sorting.ascending %}↑{% else %}↓{% endif %}{% else %}⇡{% endif %}</a>
          </th>
          <th class="text-wrap"><a href="?sort_by={% if sorting.ascending and sorting.sorting == 'departure' %}-{% endif %}departure">
              Departure
              {% if sorting.sorting == 'departure' %}{% if sorting.ascending %}↑{% else %}↓{% endif %}{% else %}⇡{% endif %}</a>
          </th>
          <th>
            <a href="?sort_by={% if sorting.ascending and sorting.sorting == 'bus' %}-{% endif %}bus">
              Bus
              {% if sorting.sorting == 'bus' %}{% if sorting.ascending %}↑{% else %}↓{% endif %}{% else %}⇡{% endif %}</a>
          </th>
          <th>Trvl</th>
          <th>Spon</th>
        </tr>
      </thead>
      <tbody>
        {% for unit in asylee_list %}
          <tr>
            <td>{% if unit.sick_covid %}<a href="{% url 'asylee:overview' asy_id=unit.id %}">{{ unit.name }}</a> ❗️{% elif unit.householdhead.is_sick_covid %}<a href="{% url 'asylee:overview' asy_id=unit.id %}">{{ unit.name }}</a> ⚠️{% else %}<a href="{% url 'asylee:overview' asy_id=unit.id %}">{{ unit.name }}</a>{% endif %}</td>
            <td><a href="{% url 'headofhousehold:overview' hoh_id=unit.householdhead.id %}">{{ unit.householdhead.name }}</a></td>
            <td class="text-center">{% if unit.householdhead.lodging %}{{ unit.householdhead.lodging }}{% else %}<small>n/a</small>{% endif %}</td>
            <td>{{ unit.householdhead.destination }}</td>
            <td class="text-right">{{ unit.householdhead.intakebus.arrival_time|time_to_now_abs:True }}</td>
            <td class="text-center">{% if unit.householdhead.travel_plan %}{{ unit.householdhead.travel_plan.departure_time|mdYIMp }}{% else %}<a href="{% url 'travelplan:add' hoh_id=unit.householdhead.id %}"><span class="text-danger">✛</span></a>{% endif %}</td>
            <td><a href="{% url 'intakebus:overview' ib_id=unit.householdhead.intakebus.id %}">{{ unit.householdhead.intakebus.number }}</a></td>
            <td>{% if unit.householdhead.travel_plan %}<a href="{% url 'travelplan:detail' tp_id=unit.householdhead.travel_plan.id %}"><span class="text-success">✓</span></a>{% else %}<a href="{% url 'travelplan:add' hoh_id=unit.householdhead.id %}"><span class="text-danger">✛</span></a>{% endif %}</td>
            <td>{% if unit.householdhead.sponsor %}<a href="{% url 'sponsor:detail' spon_id=unit.householdhead.sponsor.id %}"><span class="text-success">✓</span></a>{% else %}<a href="{% url 'sponsor:add' hoh_id=unit.householdhead.id %}"><span class="text-danger">✛</span></a>{% endif %}</td>
          </tr>
        {% empty %}
          <tr>
            <td class="bg-light text-center font-italic" colspan="4">No results found matching your query.</td>
          </tr>
        {% endfor %}
      </tbody>
        <tfoot>
          <tr>
            <th>Asylee Name</th>
            <th>Household of</th>
            <th>Rm #</th>
            <th>Dest.</th>
            <th> Here Since</th>
            <th class="text-wrap">Departure</th>
            <th>Bus</th>
            <th>Trvl</th>
            <th>Spon</th>
          </tr>
        </tfoot>
    </table><br><br>
  </div><br><br>
  <div class="jumbotron">
    <p class="lead">An Asylee is considered active if they have not yet left or are within 24 hours of arriving at their destination.</p>
  </div>
  <script  type="text/javascript">
    var $rows = $('.table > tbody tr');
    $('#search').keyup(function() {
      var val = $.trim($(this).val()).replace(/ +/g, ' ').toLowerCase().split(' ');

      $rows.hide().filter(function() {
        var text = $(this).text().replace(/\s+/g, ' ').toLowerCase();
        var matchesSearch = true;
        $(val).each(function(index, value) {
          matchesSearch = (!matchesSearch) ? false : ~text.indexOf(value);
        });
        return matchesSearch;
      }).show();
    });

    function AsyleeSearch() {
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("asylees_search");
      filter = input.value.toUpperCase();
      table = document.getElementById("asylee_list");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[0];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }       
      }
    }
    
    function HouseholdSearch() {
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("households_search");
      filter = input.value.toUpperCase();
      table = document.getElementById("asylee_list");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[1];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }       
      }
    }
    
    function DestinationSearch() {
      var input, filter, table, tr, td, i, txtValue;
      input = document.getElementById("destination_search");
      filter = input.value.toUpperCase();
      table = document.getElementById("asylee_list");
      tr = table.getElementsByTagName("tr");
      for (i = 0; i < tr.length; i++) {
        td = tr[i].getElementsByTagName("td")[3];
        if (td) {
          txtValue = td.textContent || td.innerText;
          if (txtValue.toUpperCase().indexOf(filter) > -1) {
            tr[i].style.display = "";
          } else {
            tr[i].style.display = "none";
          }
        }       
      }
    }
  </script>
  <br><br>
{% endblock %}